### ISSUE TITLE
Not all content loading from Spotify

### ISSUE THREAD

**Issue by adamtobey** [jaedb/spotmop#103]
When loading albums from Spotify, only the first 40 alphabetically appear, no matter what view I'm using. Tiled and list view will load dummy entries, and the detailed list view just stops loading. Only a certain number of my songs appear when looking in that tab too. The behavior is consistent on both Chromium and Firefox. Everything else works fine. (BTW love the app otherwise!)

Spotmop version: 2.7.1
Mopidy version: 2.0.0-2
System: Arch Linux x64, 4.6.1-2 Arch kernel, unmodified
Browser: Chromium 51.0.2704.103-1, Firefox 47.0-2

Javascript log from page:

> The key "user-scaleable" is not recognized and ignored.
> Pusher connected as 7d0312e75c0340d98f5f800e2ebc573f

**Comment by adamtobey** [comment]
Confirmed fixed. Thank you so much for the quick and conclusive fix!

**Comment by jaedb** [comment]
@adamtobey No worries! It's always good having extra eyes as this project gets bigger. More complex = more stuff to remember to check/test and patch :-)
