### ISSUE TITLE
[Feature request] Auto Update

### ISSUE THREAD

**Issue by wilderkaiser** [jaedb/spotmop#109]
Hi - first let say say thank you for this great work --- would it be possible to add a auto update function/button?

Kind regards Joerg

**Comment by jaedb** [comment]
Hi @wilderkaiser auto-update is a bit of a tricky one, but possible. Currently it's recommended to upgrade via command-line (`pip install --upgrade Mopidy-Spotmop`) or by using the (beta) upgrade functionality within the _Settings_ tab.

Have you tried using this _Settings_ tab upgrade functionality?

**Comment by jaedb** [comment]
This issue was moved to jaedb/Iris#14
