### ISSUE TITLE
Set default host and port in config file

### ISSUE THREAD

**Issue by matmar-91** [jaedb/spotmop#110]
It would be great if we can set default host and port for mopidy server somewhere in config file. For now I need to setup this for every new browser / device I want to connect.

**Comment by jaedb** [comment]
@matmar-91 Can you please provide me with some examples of your configuration?

By default the web interface will use the same ip/domain and port 6680 for it's initial Mopidy connection. For example if your mopidy server was `music.desktop` then the web interface would connect to `music.desktop:6680`.

The only time I think this wouldn't work out of the box is if your webserver was hosted on a different machine to the mopidy server (ie `spotmop.laptop` as web interface and `mopidy.desktop` as mopidy server). In this instance the `~/.config/mopidy/mopidy.config` file will not be relevant. The solution that comes to mind is to have an additional web interface config file, but this isn't a desirable solution.

I would be inclined to focus on #102 as this would provide synchronicity across your client devices.

**Comment by matmar-91** [comment]
Ok, you're right. For some reason i can't get it work first time but now i reset all settings and leave host and port blank and it worked. Probably before there was some other problem on my end. Thank you for your time and great work!

**Comment by jaedb** [comment]
Sweet, glad you got it working :-)

The _Reset all settings_ button has saved my bacon a few times too!
