### ISSUE TITLE
[Feature request] Add option to sort albums/playlists/artists

### ISSUE THREAD

**Issue by ghost** [jaedb/spotmop#111]
it's more convenient to have albums sorted by date added since the latest albums i've added are the ones i'm more into at that time.

might be a good option for tracks/artists/playlists as well.

**Comment by jaedb** [comment]
@bigmittens I think this is a great idea, especially as Spotify's default ordering is a bit... well crap.

I've lodged a request with Spotify to allow their web API to accept sort parameters, however I can't imagine this will happen quickly. The reason it needs to happen at Spotify's end is that the lazy-loading would create an unexpected user experience.

For example, sorted A-Z of 200 items. You scroll down the first 50 records (to F, let's say) and the the lazy-loader fetches the next 50 items. Some of these include items starting A-F, which would be injected further up the list. You can imagine the confusion it would create.

I'll harass Spotify again and start thinking about some alternative ways we can achieve this.

**Comment by ghost** [comment]
great answer, thanks.

**Comment by jaedb** [comment]
PS. For reference here's the issue on the Spotify Issue Tracker: https://github.com/spotify/web-api/issues/75

**Comment by jaedb** [comment]
@bigmittens I've recognised the need for this functionality to a point where I've decided to build it anyway. The obvious downside is as mentioned earlier, but with that in mind, sorting is fully operational on the `develop` branch and will be included in the next release.

**Comment by jaedb** [comment]
Amended to use the new dropdown functionality
