### ISSUE TITLE
Displayed spotify album total time is 40% shorter than it should

### ISSUE THREAD

**Issue by Zbuben** [jaedb/spotmop#114]
Hello,

the time calculated for an spotify album is too short, I took a look in the app.js file and saw that totalTime was divided by 100000 instead of 60000... I don't have any local collection so I don't know if 60000 is also good for local albums ... 

Regards,

Christophe.

ps: Here's an example, this album is near 16 minutes and is displayed 10.

![capture du 2016-07-23 19-00-10](https://cloud.githubusercontent.com/assets/10251751/17079157/e628bb0e-5107-11e6-8409-bf81b9bbb8b4.png)

**Comment by Zbuben** [comment]
Just tested with local tracks, seem affected the same way.

**Comment by jaedb** [comment]
@Zbuben Eagle eyes over here! Nice spotting dude, must have been a total lapse of programming concentration :-)

**Comment by Zbuben** [comment]
I got lucky, I was skim-reading some spotmop source code and asked myself where this 100000 came from ... I didn't pay attention to this earlier. Pretty fun indeed. ;)

Have a good day (and thanks for your good work on this project) :)
