### ISSUE TITLE
[Feature request] Tunein

### ISSUE THREAD

**Issue by patatman** [jaedb/spotmop#117]
Hi,

I really like your web-client, and i mainly use spotify. 
But occasionally i'd also like to listen to some TuneIn radio, is it possible to implement Tunein? 

Thanks!

**Comment by jaedb** [comment]
In _theory_ you should be able to install any extra Mopidy extensions and they should play within Spotmop. You can search all Mopidy extensions by using the _Other_ tab in the search results.

Here is the extension it looks like you're after: https://github.com/kingosticks/mopidy-tunein but it doesn't look particularly active so it may be a little outdated. I'll have test run with it myself too for curiosity!

**Comment by patatman** [comment]
Will give it a try,  I already have the extention installed. 
I'm also curious about your tests. It's a shame I can't write python yet :-( 
I Gave a quick look at the code,  and see if I can hack some sort of menu in there but I couldn't figure it out yet haha.

**Comment by bargru** [comment]
The source code of the search controller shows that the search only takes place in "local" and "soundcloud". Change `MopidyService.search (query, false, ['soundcloud:', 'local'])` to `MopidyService.search (query)` and it works with any extension (also TuneIn). 

If many extensions are installed, the search results are very confusing. It would be useful to filter for individual extensions.

**Comment by jaedb** [comment]
Ah, you're right there. I was hoping to be able to show all results across all `BackendExtension`s however there is no facility to list those that are installed. This would be required to facilitate filtering by source/`BackendExtension`.

That being said, I'll remove the filter on `BackendExtension`. Please note that this will mean you'll get search results for Spotify here as well as on the other tabs.

**Comment by bargru** [comment]
The Android App Remotedy ( [http://remotedy.com/](url) ; [https://play.google.com/store/apps/details?id=se.anil.remotedy&hl=de](url) ) is able to filter the search results. 

I think that the "extended" search is better than the "local and soundcloud" search. But the search results are useless if it is not possible to filter and if there are many results.

I will ask the Remotedy developer how he has done the filtering.

**Comment by jaedb** [comment]
This will be included in the next release. Essentially Spotmop will now use the Mopidy core for performing searches, which will allow for filtering by source. The list of sources will default to _Local_ and _Spotify_ but can be customised in _Settings_.

**Comment by jaedb** [comment]
Resolved in [v2.9](https://github.com/jaedb/spotmop/releases/tag/2.9)
