### ISSUE TITLE
Local music

### ISSUE THREAD

**Issue by MTRNord** [jaedb/spotmop#119]
Will Local MUsic supported in the future?

**Comment by jaedb** [comment]
@MTRNord to what capacity? Currently you can explore your local library from the _Local_ menu item underneath _My Music_. Is this not what you mean?

**Comment by MTRNord** [comment]
I mean that but I don't have an "Local" menu Item only
- Playlists
- Songs 
- Albums
- Artists

**Comment by jaedb** [comment]
What version of Mopidy and Spotmop are you currently running?

**Comment by MTRNord** [comment]
Mopidy Version: 2.0.0 from pip
Spotmop: 2.8.0 but I found out that it is installed with pip3 and not pip. I think that is the problem

**Comment by jaedb** [comment]
Hmm that's unusual, _Local_ has been supported for some time now, so it must be a very old version. Can you please navigate to the settings tab and take a quick screenshot of the whole window?

**Comment by MTRNord** [comment]
After installing it with pip instead pip3 it seems to work. hm maybe my pip3 is/was broken

**Comment by jaedb** [comment]
Glad you got it sorted :-)
