### ISSUE TITLE
[Feature request] Support for local playlists

### ISSUE THREAD

**Issue by bargru** [jaedb/spotmop#120]
The playlist view displays Spotify and local playlists. When you open a local playlist, the contained tracks are not displayed. In other apps Mopidy the tracks are displayed.

**Comment by jaedb** [comment]
Currently local playlists aren't supported. What format is your playlist in, `.m3u`?

**Comment by bargru** [comment]
Yes I'm using m3u playlists with the mopidy m3u extension. It would also be helpful if local playlists could be processed, created and deleted.

I do not know how far you want to develop Spotmop for not Spotifiy extensions. Unfortunately, I have little experience with JavaScrip and no with AngularJS. I am currently trying that images of local music can be displayed.

**Comment by jaedb** [comment]
Personally I use Spotify for 99% of my music. However seeing as the general idea behind Spotmop is to provide a fully-functional web-based interface for Mopidy I think supporting as many mainstream extensions as possible is ideal.

I'm also looking to improve the search functionality which will also help bridge this gap.

**Comment by jaedb** [comment]
Resolved in [v2.9](https://github.com/jaedb/spotmop/releases/tag/2.9)
