### ISSUE TITLE
[Feature request] queueing + shuffle

### ISSUE THREAD

**Issue by ghost** [jaedb/spotmop#125]
Disc: long post, just skip to suggestions if you aren't up for some squawking.

Hi,

First of all, this is the best mopidy spotify interface around. I have two suggestions which "feels" like depending on one another.

**Whining no.1**: One of the biggest features I miss from the official spotify client is to have the rest of the playlist get queued when I double click on a track, so that it'd keep playing without any further interaction. Right now, the d-click behaviour is to place that track at the top of the play queue in spotmop. the problem: it won't continue playing unless I add the rest of the playlist by hand. The only way to have that is to queue the whole list by clicking "Play" in the playlist details view and skip to the desired track, which is impractical in true sense. Moreover, adding track to the top does that it wouldn't get played as you might already be playing a track somewhere deep in the queue and you need to go all the way back.

**Suggestion no.1**: double click should: clear the queue, add rest of the playlist to the queue, restart playing from the top of the queue.

**Whining no.2**: The player lacks some of the fundamental features a music player should have: play modes and time indicators. Relating to the first issue, it's nearly impossible to have a pleasant experience without constant interaction, since you'd need to skip frequently or hand curate the queue. And it'd actually be a strong "selling point" to have an alternative to infamously lame spotify official shuffling algo. The track time and remaining time indicators are a must too, imho. That'd also allude to a revamp of left frame, possibly with more lines(vertical space) allocated to play controls at the bottom. 

**Suggestion no.2**:  play modes like repeating and shuffling should be implemented for a better playing experience.

**Comment by jaedb** [comment]
I'm glad you like it!

This is a topic that has been discussed before (#68 and #91) and it was clear that double-clicking shouldn't clear the existing tracklist. Have a look at the discussion for more information.

You do raise a good point that the double-clicked tracks shouldn't go to the top, just to where the play 'cursor' (track currently playing) is. See new issue #131.

Suggestion number two: This functionality is available on the _Now playing_ tab. The reason it is not in the sidebar is there is very little screen real estate available for more controls. I have toyed with a re-assessment of the current design, in which I'll look at other ways we can address this.
