### ISSUE TITLE
[Feature request] Control Icecast audio streaming service

### ISSUE THREAD

**Issue by svallory** [jaedb/spotmop#129]
Hey, guys! Thanks for the grate work!

What you guys think about integrating a stream player? I configured my mopidy to stream music using icecast. It would be really nice to be able to control the stream on spotmop.

What I'm thinking is that we could add a simple **hidden** stream player that would be controlled with the same controls if "listen here" is enabled. The only difference being that the volume would only mute the stream while play/pause would work as they do now.

This way we can have multiple people listening to the same mopidy stream.

**Comment by jaedb** [comment]
Glad you're enjoying using Spotmop.

My initial response is that this is well beyond scope of the project, however I think all ideas should be given a fair opportunity :-)

Can you please provide me with the steps required to replicate your environment? Is the main objective of this to facilitate other devices to play the Mopidy server's audio stream (ie multi-room setup)?

**Comment by jaedb** [comment]
This issue was moved to jaedb/Iris#13
