### ISSUE TITLE
Loading failed

### ISSUE THREAD

**Issue by akinomeroglu** [jaedb/spotmop#133]
Hello,

I install spotmop to my raspberry pi 3 via pip. Loading of spotmop fails when I restart the service. 

Hope this information enough for you and thanks for your help.

You can find log file below

`2016-08-30 12:53:19,463 ERROR [18048:HttpServer] mopidy.http.actor: Loading spotmop failed.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/http/actor.py", line 135, in _get_app_request_handlers
    request_handlers = app['factory'](self.config, self.core)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_spotmop/__init__.py", line 86, in spotmop_client_factory
    "path": config['local-images']['image_dir']
  File "/usr/lib/python2.7/dist-packages/mopidy/config/__init__.py", line 283, in __getitem__
    item = self._data.__getitem__(key)
KeyError: u'local-images'
`

**Comment by jaedb** [comment]
Have you got `Mopidy-Local-Images` installed?

**Comment by hcoohb** [comment]
Hi,

I upgraded this morning using the pip command, restarted my mopidy server
and got the same error as described.
I did not have Mopidy-Local-Images installed. I installed it and everything
is all good now.

Can we add the Mopidy-Local-Images as a dependency in the pip package so
that everything install/update smoothly?

Thanks for that new version!

Fabien

**Comment by jaedb** [comment]
@hcoohb Excellent - just as I suspected :-) Thanks for confirming this; I'll update the dependencies in the next release.
