### ISSUE TITLE
Can't find some Albums

### ISSUE THREAD

**Issue by choseh** [jaedb/spotmop#139]
Hello,

we have this quite weird issue that we can't find some albums. I can find them just fine with the regular client and we have set the country code to DE (locale de_DE). Could it be that this is currently somehow broken?

Kind regards,
Alex

**Comment by jaedb** [comment]
@choseh are you able to send me some example albums that _should_ show but don't?

**Comment by choseh** [comment]
Sure!
spotmop search results for "Deichkind": https://uploade.es/#3nz7XsQk1XLfrZSvhzU6LQ 
spotify web search results: https://uploade.es/#MZI4404pD5Cgw8Gf7suDhA

looks like https://github.com/jaedb/spotmop/issues/140 might be related

best regards,
alex

**Comment by jaedb** [comment]
Looked like the recent upgrades to the storage engine hadn't accounted for the Spotify `country` and `locale` parameters. Tested and operating as per the Spotify Web application now.
