### ISSUE TITLE
can't start radio from Albums folder

### ISSUE THREAD

**Issue by mczerski** [jaedb/spotmop#152]
if i go into Album folder (MY MUSIC) and start radio from any song it fails (nothing is played) and I can see in the log:
ERROR [3850:SpotmopFrontend-13] mopidy_spotmop.frontend: SpotmopFrontend: Failed to fetch recommendations from Spotify

the radio can be started from this songs from other folders (Track or from search) so this is not the issue with particular song.

**Comment by jaedb** [comment]
This issue was moved to jaedb/Iris#9
