### ISSUE TITLE
EXTINF in m3u playlist

### ISSUE THREAD

**Issue by mczerski** [jaedb/spotmop#154]
when I create playlist like this:
# EXTINF:1,MultiRoom

rtsp://osmc.local:5004/test

and then open the playlist in spotmop, the name of the track is the uri not the name from the EXTINF directive. In moped ui this playlist is displayed correctly.

**Comment by jaedb** [comment]
I have a confession: I'm unfamiliar with `EXTINF`. Given that Mopidy core plays this fine, I'm sure it can be achieved. It will depend on what information about the stream Mopidy makes available.

**Comment by mczerski** [comment]
ok, I thought that parsing m3u playlist is done by mopidy core. it would suffice to just show the url but this is also sometimes fail. sometimes the url is showed and sometimes there is nothing showed.

**Comment by jaedb** [comment]
This issue was moved to jaedb/Iris#8
