### ISSUE TITLE
Save now playing queue between restarts

### ISSUE THREAD

**Issue by wuservices** [jaedb/spotmop#157]
I just started using spotmop and it's awesome! It seems like the now playing queue isn't saved if you kill the server. Is this just a missing feature? Or am I just doing something wrong.

I installed Mopidy-Local-Sqlite just in case that was used for this, but it doesn't save.

Thanks!

**Comment by jaedb** [comment]
I'm glad you're enjoying it! 

This is not a function that is currently implemented and is something that I believe belongs on the Mopidy server. You can imagine the chaos if you started the server when multiple web clients were open and all tried to re-import the previous `TlTracklist`.

**Comment by wuservices** [comment]
Thanks for the insight. That makes sense. Now that I get the idea, I figured out where to look.

This was discussed in https://github.com/mopidy/mopidy/issues/310, which referenced `mopidy-qsaver`. I installed https://github.com/HeadspringLabs/mopidy-qsaver and it just works!
