### ISSUE TITLE
Spotmop installed with python-pip does not work on mopidy on Arch

### ISSUE THREAD

**Issue by fpqc** [jaedb/spotmop#158]
Not sure why, but when I reinstalled mopidy on Arch linux (had previously been on an Ubuntu VM), spotmop was no longer showing up on the mopidy http server.  This happened both when installing with the Arch AUR package and also the python-pip package.  Mopify currently works, but it is very much inferior to spotmop, so I was wondering if you could take a look into this.  Thanks.

**Comment by jaedb** [comment]
I haven't actually submitted Spotmop to Arch AUR, this appears to have been by someone else! :open_mouth: It looks like @MarcinWieczorek submitted this package.

I do manage the submission to the PyPi repository though, and this appears to be working as usual. You're using the `pip install Mopidy-Spotmop` command?

**Comment by MarcinWieczorek** [comment]
Well if this is not my fault then we need to resolve it here in the upstream, as the ArchLinux community always guides us to.

**Comment by jaedb** [comment]
@MarcinWieczorek totally agree. It looks like it's a distribution issue rather than a code issue so I'm hoping it's just that the PyPi/Arch AUR servers being down. In any case, a rebuild of Spotmop is due to launch any day now :-)

**Comment by MarcinWieczorek** [comment]
This has nothing to do with AUR servers. The package is being built at user's machine. Arch User Repository maintainers only provide scripts to automatize that process.

**Comment by fpqc** [comment]
It's working now, there's a missing dependency somewhere in the install scripts after I read my logs.  Something like "pylast" (I don't remember, I did it earlier today and forgot) or something like that.  I installed it and forgot it.  

The missing dependency is also in the pip installation, I think.

**Comment by MarcinWieczorek** [comment]
It was my fault then. `python2-pylast` package, right?

**Comment by fpqc** [comment]
@MarcinWieczorek yep!

**Comment by jaedb** [comment]
Is there any change required to the code to help ensure this dependency is met during build?

**Comment by fpqc** [comment]
@jaedb Probably, the pip installer didn't look for it either.

**Comment by MarcinWieczorek** [comment]
Just to make sure, it's `mopidy-spotmop` package? I'm always getting lost, they're so similar

**Comment by fpqc** [comment]
@MarcinWieczorek yep!

**Comment by fpqc** [comment]
@jaedb I just realized, I installed with pip instead of pip2.7, that was maybe the problem.

**Comment by MarcinWieczorek** [comment]
I've pushed the update
