### ISSUE TITLE
Show playlist name in Now Playing

### ISSUE THREAD

**Issue by antonsmithnz** [jaedb/spotmop#164]
First of all, love the work you have done on this amazing frontend! Thanks heaps!

In our office, person A will add a playlist to the Now Playing queue. Person B, C and D will often ask 'what playlist is that'? This happens every day lol.

It would be cool if Spotmop showed the current playlist name (if any) in the Now Playing area and linked off to it so others in the office can discover the playlist if they like it.

**Comment by hcoohb** [comment]
Hi,  I like that idea, that would be an awesome feature!

**Comment by jaedb** [comment]
This is a neat idea, and Spotify manages to pull this off in their application. When building this from scratch (as we would need to do) there are a few tricky bits to consider. For example: what if we add other tracks to the queue, at what point have we 'finished' playing the playlist?

**Comment by jaedb** [comment]
This issue was moved to jaedb/Iris#4
