### ISSUE TITLE
Many playlists and API rate limiting

### ISSUE THREAD

**Issue by sgraca** [jaedb/spotmop#167]
I have many playlists (over 200) and this seems to cause some issues when I start Spotmop. It tries to load all of them during startup which takes some time (the application makes over 600 request in total), and before that I cannot use the application. But I also noticed that load calls to load the playlist details fail with HTTP error 429:

```
HTTP/2.0 429 No Reason Phrase
Server: nginx
Date: Sat, 31 Dec 2016 12:21:41 GMT
Retry-After: 3
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 604800
Access-Control-Allow-Headers: Accept, Authorization, Origin, Content-Type
Content-Encoding: gzip
X-Firefox-Spdy: h2

{
  "error": {
    "status": 429,
    "message": "API rate limit exceeded"
  }
}
```

**Comment by jaedb** [comment]
This issue was moved to jaedb/Iris#3
