### ISSUE TITLE
Project needs a license

### ISSUE THREAD

**Issue by jodal** [jaedb/spotmop#36]
I noticed that Spotmop doesn't include a `LICENSE` file or text in the `README` indicating what license the software is licensed under. The `setup.py` file says Apache 2, but I'm afraid that was simply copy-pasted from another project and not a conscious choice?

As long as the project doesn't have an explicit license it is strictly speaking not open source and cannot be used by anyone without your explicit permission.

**Comment by jaedb** [comment]
Hi @jodal good spotting. I'm still getting my head around how python hangs together, so it's good to know what still needs doing. Originally I was using Apache 2 + PHP code, but have since decided to move towards python backend providers.

That being said, I did use `Mopidy-Mopify` as a start point for my `setup.py` file.

**Comment by jodal** [comment]
It's awesome that you've moved to packaging Spotmop as a Mopidy extension. That makes it a lot easier to get up and running!

As for choosing a license, it is up to you as the author, but remember to think about licenses when copying code from other projects. For example, Spotmop includes some code from Mopidy-Mopify which is Apache 2-licensed. If you want to keep that code around, you're limited to using Apache 2 or any compatible license yourself.

We (as in the Mopidy project) tend to recommend permissive licenses (Apache/MIT/X11/BSD) and also require that for a project to be listed in our docs. I have the change ready to include Spotmop with a screenshot in the Mopidy docs, but would like it to have a permissive license first. No pressure ;-)

To learn more about licenses, https://tldrlegal.com/ can be a useful resource.

**Comment by jaedb** [comment]
I've just plugged in the Apache 2.0 license now (5ecb8fc). Is there anything else i need to do to link the project to the license (ie on PyPi)?

**Comment by jodal** [comment]
You might want to state in the README that the project is licensed under the "Apache License, Version 2.0", but there's no requirement.

**Comment by jaedb** [comment]
License stated and included as at 2170668. Please let me know if there's anything else I need to do to gain a listing on the Mopidy docs, thanks!
