### ISSUE TITLE
Use Mopidy-Spotify for Spotify requests instead of re-authentication and use of Spotify HTTP API

### ISSUE THREAD

**Issue by damian-w** [jaedb/spotmop#42]
Fresh install of Spotmop & Mopidy.

Pop-up asking for the user to connect their Spotify account by logging in, even when the account I want to use has already been defined in the Mopidy configuration file.

Hopefully going to use Spotmop in a co-working space :)

**Comment by kierwils** [comment]
Exact same issue here, clean install on Raspbian Jessie, also want to use in the office

**Comment by jaedb** [comment]
The main driver for developing this was for our office environment too - so I'm glad it has appeal for others.

Currently the Mopidy config file's credentials are used in the `Mopidy-Spotify` backend and are not available for use in the frontend. Basically Spotmop uses additional Spotify endpoints that aren't currently available on the `Mopidy-Spotify` backend, so you will need to authenticate again. A bit niggly, but I'm working on some improvements in this area.

When you enter your login credentials in the popup, do you continue to get requests for authentication?

**Comment by damian-w** [comment]
> When you enter your login credentials in the popup, do you continue to get requests for authentication?

No, just once!

Trying to implement Spotmop in a co-working space, but not many individuals have Spotify which won't be too good :/ We were just planning on using our "group" Spotify account.

Any idea when Spotmop won't require this secondary authentication?

**Comment by jaedb** [comment]
@damian-w we have a similar problem at our office, and we resolve it by having everyone login to Spotify using the same login details. Because the music is only playing on one server (despite multiple people using the single authentication to browse), you won't encounter any issues.

At this point the `Mopidy-Spotify` backend doesn't provide all of the functionality required by Spotmop, so until this happens we'll need to authenticate using the Spotify web API. Development on `Mopidy-Spotify` is steady, and I'm keeping an eye on it's progress, so this issue may be revisited.

**Comment by damian-w** [comment]
> we resolve it by having everyone login to Spotify using the same login details.

@jaedb I'd love to do this, but being a public co-working space we wouldn't be able to trust the countless visitors we encounter daily with our Spotify account! :/

If you ever develop a work-around / ability to set a default Spotify account to login to, give me a shout and we'd be most certainly happy to help test it out!

**Comment by jaedb** [comment]
@damian-w Unfortunately after further investigation this is quite involved and would require work on the `Mopidy-Spotify` extension (https://github.com/mopidy/mopidy-spotify). I wouldn't expect this to be resolved in the short term, but keep an eye on development in this area.

**Comment by damian-w** [comment]
@jaedb Dang! How about a default Spotify account? Say have a configuration file where I can set the username and password of our Spotify account, and it'll automatically login?

**Comment by jaedb** [comment]
The way that Spotify works is by using OAuth, and this requires the user to login with their credentials to 'authorize' the application to use said user account. Then using that authorization we generate a token which is required for the majority of the Spotify endpoints. This means that without Spotify authorization Spotmop is highly limited.

That being said, I'm exploring an option to make it operable, even without authentication. See branch [`feature/publicspotify`](https://github.com/jaedb/spotmop/tree/feature/publicspotify)

**Comment by jaedb** [comment]
@damian-w I've just pushed up a version to the branch `feature/publicspotify` that is ready for testing. Are you able to clone this repo and install a development version of Spotmop?

**Comment by damian-w** [comment]
@jaedb awesome! I'm on leave, but I'll get another member of the team to look into it! :)

**Comment by jaedb** [comment]
Have a hoon on v2.5.10 which I've just released :-)

Please note that loading playlists is very slow for some reason. I suspect due to accessing via Mopidy backend via Mopidy-Spotify via Spotify API...

**Comment by jaedb** [comment]
Reasonable compromise achieved - 90% functionality without requiring Spotify Client Authorization. Please re-open this issue if you find this functionality doesn't work as expected.
