### ISSUE TITLE
Integrate Youtube and SoundCloud in search

### ISSUE THREAD

**Issue by ghost** [jaedb/spotmop#44]
It would be awesome to be able to search these to services, perhaps even create somekind of custom playlist, where you can add YT, SC and Spotify tracks.

**Comment by jaedb** [comment]
Agree - at some stage it would be good to implement more sources. I have also considered Google Music. At this stage the focus is on Spotify and local files, but will start thinking about the best way to expand to these media sources.

**Comment by ghost** [comment]
Great! 
I actually think that mopify has basic implementation of youtube, so perhaps possible to get inspiration from there :)

**Comment by jaedb** [comment]
It looks like the `Mopidy-Youtube` extension is quite basic, so I'm wary of the level of involvement to get this running to the same quality as Spotify and Local files.  I'll flag this functionality for a future release when that extension becomes a bit more stable.

**Comment by jaedb** [comment]
PS. I have integrated the Soundcloud backend into the player functionality. You can now add items via URI (across all supported backends) as at `2.6.2` 1ec26f7. I'll continue to explore what the best way is to integrate into the UI itself.

**Comment by jaedb** [comment]
Basic integration in place for Soundcloud as at `2.6.3`. This will be improved as we go to add browsing etc.
