### ISSUE TITLE
Can't get featured to show other countries than NZ

### ISSUE THREAD

**Issue by ghost** [jaedb/spotmop#46]
No matter what I do, I can't get other countries featued playlists to show

**Comment by jaedb** [comment]
Identified as issue with settings field vs setting value. Resolved in bb325d1fc9826d02aea8a8d776e85c528eed5526 and packaged for next release (`2.5.4`)

**Comment by jaedb** [comment]
@Kantraz this is now released

**Comment by ghost** [comment]
Fantastic! 
I must say I really like this UI, much faster and prettier than mopify!
