### ISSUE TITLE
webpage not found

### ISSUE THREAD

**Issue by hcoohb** [jaedb/spotmop#49]
After install and restart of mopidy, I cannot access the webpage.
When going to the url, I have a 404 page not found.
I am using a raspberry pi with raspbian Jessie distribution

I am not sure what to do to have it working

In my log of mopidy I have the following:
INFO     Starting Mopidy 1.1.2
INFO     Loading config from builtin defaults
INFO     Loading config from /home/xxxx/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mopify, spotify, alsamixer, http, file, spotmop, spotify_tunigo, softwaremixer, moped, musicbox_webclient
INFO     Disabled extensions: soundcloud, mpd, local, m3u, stream
INFO     Starting Spotmop web client 2.5.7
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Mixer volume set to 80
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: FileBackend, SpotifyTunigoBackend, SpotifyBackend
INFO     Audio output set to "alsasink"
INFO     Starting Mopidy core
INFO     Logged in to Spotify in offline mode
INFO     Logged in to Spotify in online mode
INFO     Starting Mopidy frontends: HttpFrontend, QueueManagerFrontend
INFO     HTTP server running at [::]:6680
ERROR    Loading spotmop failed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/http/actor.py", line 133, in _get_app_request_handlers
    request_handlers = app['factory'](self.config, self.core)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_spotmop/__init__.py", line 58, in spotmop_client_factory
    application.listen(pusherport)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1825, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 196, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

**Comment by jaedb** [comment]
It looks like the default port that the push notifications system uses (port 6681) is in use. You will need to set Pusher to use a different port. To do this, edit your config file (_/home/xxxx/.config/mopidy/mopidy.conf_) and add the following lines (where _xxxx_ is your desired port number):

```
[spotmop]
pusherport = xxxx
```

This will change the port for the Pusher server, but remember you'll need to specify this in the web interface too. To do this, go to Settings and then change the port under 'Notifications Port'.

**Comment by hcoohb** [comment]
Hi,

Thank you for the quick answer!
Yes, there was definitely a session of ympd running on that port. Stopping ympd solved the issue. 
I think I'd rather change the port for ympd so I have a simple setup for spotmop.

And btw, I really like spotmop, more responsive than mopify from my early testing
Thanks for your efforts!

**Comment by hcoohb** [comment]
(Just as a comment, I will close the issue, but it would maybe be worth mentioning that setup in the main github page)
Cheers

**Comment by jaedb** [comment]
@hcoohb good point, I'd like to create a proper documentation page but for now I've added this to the readme (c10aa62). Glad it's working for you now!

**Comment by Firesphere** [comment]
I still get a 404 not found on any port I try, sadly. 6680 is not responding, any pusherport gives me a 404
