### ISSUE TITLE
Better support for Local MySQL

### ISSUE THREAD

**Issue by LasseSLambertsen** [jaedb/spotmop#50]
When using MySQL for local track database, not all categories entries are populated;
artist, album, release years, composers, performers

**Comment by jaedb** [comment]
The Mopidy MySQL-based library must be a slight deviation of format from the local JSON library. It'll require further investigation. Watch this space.

**Comment by jaedb** [comment]
@LasseSLambertsen I'm working on this now and am hoping to include a basic patch in the next release. I'd like to spice the local files area up a bit to align with the Spotify-sourced look and feel, but that's a few releases away. Just wanted you to know that it is coming :-)

**Comment by LasseSLambertsen** [comment]
@jaedb Sounds great, looking forward to it!

**Comment by jaedb** [comment]
Note to self: Also need to address `TlTrack` interactivity (ie artist and album links). Will need a sub-class of `TlTrack` for local files.

**Comment by jaedb** [comment]
@LasseSLambertsen It's a tricky issue that I haven't quite cracked. There seems to be a discrepancy between how Mopidy provides the "folders" (in this case categories) and how it expects them to be requested. In any case I've made _some_ improvements into the handling of local libraries, see `v2.5.16` (22d5089).

**Comment by jaedb** [comment]
@LasseSLambertsen I've just pushed up a new version that addresses some of the issues around the local file library. It'd be great to see if this fixes the issues that you were experiencing, are you able to have a look and let me know?

You can get the latest by pulling the `develop` branch.

**Comment by LasseSLambertsen** [comment]
Seems, to be fixed now :)
Cheers man!

**Comment by jaedb** [comment]
Sweet! This will be included in the next release.

**Comment by jaedb** [comment]
@LasseSLambertsen I've just released a rebuilt version of the local library that utilises the current artist/album templates. This will only work for the SQLite extension, the standard JSON library will remain pretty basic. See version `2.7.0`.

**Comment by LasseSLambertsen** [comment]
@jaedb Oh nice, gonna check it out tomorrow! 
Wish I could be of any help coding this, but don't have any experience in python :/

**Comment by jaedb** [comment]
Hah, no worries. I'm a total python newbie too, my background is in website design and development so this has been a rather large project with a decent learning curve!

**Comment by LasseSLambertsen** [comment]
Perhaps I should try to clone it, and look into it :)
