### ISSUE TITLE
German Umlauts not working in Search

### ISSUE THREAD

**Issue by choseh** [jaedb/spotmop#51]
Hello,

unfortunately searching for artists with german umlauts in their names is currently not working.

Steps to reproduce:
- Search for Blümchen
- no Blümchen :(

(http://hostname:6680/spotmop/#/search/Bl%C3%BCmchen/artist)

Cheers,
Alex

**Comment by jaedb** [comment]
Good spotting - I've now patched this and released a new version that resolves this issue. See in release `2.5.9` or commit 8e1cac3bb64f1e6987396c10a3d470ad96051fa9.
