### ISSUE TITLE
Feature Request: Support for Veto Threshold

### ISSUE THREAD

**Issue by choseh** [jaedb/spotmop#52]
Here in the office it would be nice to have a configurable veto threshold.

"3 people vetoed this track, skipping"

Thanks in advance

**Comment by jaedb** [comment]
Hi, thanks for your feedback! Are you thinking it'd work kinda like [Apollo Player](https://github.com/samcreate/Apollo-Player)?

**Comment by choseh** [comment]
Hey,

yeah, pretty much like Apollo.

Thanks in advance

**Comment by jaedb** [comment]
@choseh Currently when a track is 'vetoed' it is an indication that a user has skipped said track. Unlike Apollo, Spotmop doesn't require a certain level of votes to action a skip - it happens immediately. It might be a nice feature to have further down the line though!
