### ISSUE TITLE
Spotmop does not work with HTTPS

### ISSUE THREAD

**Issue by qurben** [jaedb/spotmop#53]
I tried installing spotmop in my Mopidy installation, but I am unable to play files, because spotmop tries to do requests over HTTP, which isn't allowed by the browser.

Websocket connections are also done over non-secure websockets.

**Comment by jaedb** [comment]
What kind of browser are you using that prevents HTTP requests?

**Comment by qurben** [comment]
I am currently using Mozilla Firefox 43.0.4

When I load the page I can see the progress of the current song and use the Play/Pause button.

Explicitely allowing http request allows me to see my playlists. Next/previous doesn't work at all.

**Comment by jaedb** [comment]
Can you please provide more information about why your setup requires HTTPS requests? Are you using a proxy or similar network setup?

**Comment by qurben** [comment]
I recently moved my entire infrastructure over to HTTPS, with Let's Encrypt. Mopidy is running behind nginx.

It is not required to use HTTPS, but the internet is slowly moving away from HTTP. That said, detecting a secure connection and using it isn't a complex thing to do.

**Comment by jaedb** [comment]
Hi @qurben have you had any experience with HTTPS and Python's Tornado and Websockets servers? If so, you might be able to help me implement this :-)

**Comment by jaedb** [comment]
Closing issue as no interest has been expressed in making this happen. Currently out of scope on my work programme. If someone is interested in contributing to this, please let me know.
