### ISSUE TITLE
Access Token fetching

### ISSUE THREAD

**Issue by wezzynl** [jaedb/spotmop#61]
Would be nice to allow users to handle their own Access Token fetching in stead of going through a PHP file on some server where we don't know what's actually being done there.

Seems Spotify also allows for Implicit Grant Flow (https://developer.spotify.com/web-api/authorization-guide/#implicit_grant_flow) it would then redirect directly to the app's callback URL with the Access Token. No server-side code is then needed, however I think the Access Token is then short-lived which may not be a problem when it would re-request Auth when the Access Token is expired.

**Comment by jaedb** [comment]
@wezzynl Unfortunately the Implicit Grant Flow requires a whitelist of all valid `redirect_url`s. Basically this would mean for every user I would need to add their IP address or domain to the Spotify App's whitelist. While this was fine when it was just a small project that only I was using, it's really viable now.

Basically the off-site request goes to a public domain (which is whitelisted) and generates an `access_token` and `refresh_token`, which are then passed back to Spotmop.

Feel free to tinker and see if you can find a way to make this work though - the Spotify authentication is the slightly more cumbersome area that would be nice to simplify.

**Comment by wezzynl** [comment]
@jaedb sure it requires a whitelisted redirect_uri but if users could specify their own Spotify OAuth App then those who'd want could just do that; create an OAuth App after registering as Spotify dev and off they'd go.

If I can find time to tinker, I'll certainly will. However time is scarce, which is why I want to thank you for your efforts. Great UI!

**Comment by jaedb** [comment]
Related discussion: #74
