### ISSUE TITLE
[Feature request] Currently playing tracks 'added by' property

### ISSUE THREAD

**Issue by atze234** [jaedb/spotmop#67]
Hi,
it would be nice to see which Spotmop user added a Song to the actual running Playlist. Is it possible to add a User Column to Now Playing? 

Thank you for this wonderful Mopidy Frontend :)

**Comment by jaedb** [comment]
@atze234 I agree! This is something that I started looking in to, but it will require some Mopidy backend coding to handle the users from across multiple connections and then store that user data for each track. It's tricky business but it is on the list!

**Comment by jaedb** [comment]
This issue was moved to jaedb/Iris#16
