### ISSUE TITLE
Feature Request: Disable Play on Double Click 

### ISSUE THREAD

**Issue by atze234** [jaedb/spotmop#68]
When Doubleclicking a Song the Running Playlist is truncated. Would'nt it be nice when the doubleclicked Song is added to the Playlist instead?
Same for the "Play" Button in Context Menu.

**Comment by jaedb** [comment]
@atze234 Interesting feedback. I wasn't 100% sure how to design this interactivity so used Spotify's app as a benchmark. I guess it comes down to what the user expects to happen.

Is the desired behavior of double-click the same as what the context menus's "Add to queue" current does?

**Comment by choseh** [comment]
@jaedb maybe add an option to configure the desired behavior of double clicking? I share the office with @atze234 and yes, sometimes someone doubleclicks a song and the entire playlist is empty ;)

**Comment by atze234** [comment]
Yep, i think it would be better doing the "Add to queue" on doubleclick ;)

**Comment by jaedb** [comment]
@atze234 I've come to realise you're absolutely right. Many of the users at our office 'get it', but natural behavior is to double-click to play the song immediately. Even if the intent was to continue playing the tracklist once said track finishes.

Anyway, I've adjusted the functionality and expect to release in version `2.6.5` as at 2030f34993f4e856830a2b67b146c14cd93071a0
