### ISSUE TITLE
Feature request: Server-managed Spotify authentication

### ISSUE THREAD

**Issue by allo-** [jaedb/spotmop#74]
Each time i open spotmop, i need to enter a name and reauthenticate with spotify.
Spotify music in mopidy continues working, but the web interface needs a new authentication.
- Mopidy-Spotify (3.0.0)
- Mopidy-Spotmop (2.5.14)

**Comment by jaedb** [comment]
It might be possible that `localstorage` isn't supported on your browser if it's an older version. What browser and OS are you running?

**Comment by allo-** [comment]
Chromium. It's possible, that localstore is cleared in between and i wanted to use different computers.
Why isn't the login stored server side? The credentials are configured for mopidy anyway, so another api token won't harm, i guess.

**Comment by jaedb** [comment]
`localstorage` is essentially just a cache that is per browser per computer. So if you were to clear your browser cache, use incognito mode, use a different computer or browser then those cached values will not be used. Is this the type of scenario that you're describing?

The configuration of login credentials within the `mopidy.conf` file are for the Mopidy-Spotify backend and are separate to the frontend.

**Comment by allo-** [comment]
Yes. So let's ask the other way round: Can the credentials be stored server side in some way?
Best, if they could not be retrieved via the client, so people can for example control an open mopidy server and play all music without knowing my login details.

**Comment by jaedb** [comment]
Yes and no. They could be, but that deviates from the current scope of the project. The key idea is to have a self-contained web interface (for now) as my experience in Python is limited, at best.

On a side-note, having Mopidy server handle authentication is great except that any changes any user makes to the playlists, following, my albums, etc will affect all users using that Mopidy server. I can also see the benefit to this though!

So for now, it's out of scope. That being said, if you are savvy with Python and keen to help then we can certainly look to address this.

**Comment by allo-** [comment]
Hmm, i do quite some stuff in python, but did not yet work on anything mopidy related.
I guess it's mostly about an authentication token? Possibly it could just be stored / loaded via AJAX as it is.

Maybe mopidy has some way to store values in the config / in other mopidy related files/databases.

**Comment by v1nc** [comment]
I like your project very much, but its useless for me if the credentials are only stored client sided. You throw away every advantage mopidy has. If someone wants to play music just from one device, he can just do it from the device and not over a server. Its very sad, that this is out of scope for you, I'm new to mopidy extensions, but i think client side saving is harder to do than server sided with the mopidy.conf. If you have time, you can maybe look at the Musicbox-Webclient extension, because it stores the credentials server sidet.

**Comment by jaedb** [comment]
@v1nc thanks for your feedback.

It is worth noting that this limitation is not a limitation of Spotmop. It is due to how Spotify handles authentication. In many cases server-side (aka _Client Credentials flow_) authentication is sufficient. You can use this by not logging in to Spotify via Spotmop.

> The _Client Credentials_ flow allows you to get an access token by supplying your client credentials (client ID and secret key). This flow is used in server-to-server authentication. Only endpoints that do not access user information can be accessed. Its advantage is that a higher rate limit is applied compared with requests to the Web API made without an access token.

However, for several Spotify API endpoints we require user-specific information that requires the _Authorization Code_ flow. This can not be performed server-side. For example _My Tracks_, _My Albums_, etc.

> The _Authorization Code_ flow first gets a code then exchanges it for an access token and a refresh token. Since the exchange uses your client secret key, you should make that request server-side to keep the integrity of the key. An advantage of this flow is that you can use refresh tokens to extend the validity of the access token.

Hopefully this helps you understand the reason this is not currently viable. For more information, visit [Spotify Authorization GUide](https://developer.spotify.com/web-api/authorization-guide/).

**Comment by allo-** [comment]
I think a flow sending the authentication token (i think it's an oauth method?) to the server to store it there would be possible. If the token is sent to (new) clients or if all api access is made by the server (better protecting the token) can be changed later.
From an concept point of view, maybe even mopidy should store the token in some way, that all plugins can access it, for example spotmop and some mobile web plugin. But this would make this issue a lot bigger then.
The first solution would be to send the token to the server after getting it and retrieve it on the client if the localstorage is empty.

**Comment by jaedb** [comment]
After re-reading the initial discussion, I'd like to clarify that Spotmop works perfectly fine without authenticating Spotify via _Authorization Code_ method. It's just you cannot access some newer Spotify endpoints (like _My Tracks_, _My Albums_, etc).

For more information there is a discussion around this on the `Mopidy-Spotify` extension: https://github.com/mopidy/mopidy-spotify/issues/16

**Comment by allo-** [comment]
I guess this are two issues:
- What new features can mopidy provide, so the interface does not need to know the token anymore
- How to store any data server side (i.e. settings, even trivial stuff like abackground color which should be synced to all clients).

**Comment by jaedb** [comment]
That's precisely the issue - Mopidy currently doesn't support Spotify's new endpoints. This is why Spotmop supports the option to use Mopidy's backend Spotify authentication, or the more capable _Authorization Code_ flow.

**Setup one** (no user-authenticated Spotify account):
- Unselect "Connect with Spotify" on initial setup
- Don't have a Spotify account, or don't want to use _Authorization Code_ flow
- All requests use the `Mopidy-Spotify` backend
- New Spotify endpoints and functionality that is not supported by `Mopidy-Spotify` is disabled. This includes _My Albums_, _My Tracks_ and _My Artists_ as they require additional authentication scopes.
- All other functionality remains (browsing playlists, playing music, browsing local library, etc)

**Setup two** (user-authenticated Spotify account):
- Select "Connect with Spotify" on initial setup (default)
- If existing setup, click "Login to Spotify" on the _Settings_ tab
- _Authorization Code_ flow uses popup and external server to complete authorization and provide tokens
- All Spotify requests use these tokens
- New Spotify functionality enabled (_My Albums_, _My Tracks_ and _My Artists_)

The reason Setup two is the default and preferred setup is that communicating directly with the Spotify Web API allows for a more streamlined and lightweight interface (only loading on demand). It also means the interface is less dependent on a powerful Mopidy server. This will continue to be the preference for Spotmop.

This means Spotmop works perfectly well on low-powered devices like the RaspberryPi. It also means you can continue to browse music while the Mopidy server is performing other requests (like batch loading a lot of tracks).

This issue has deviated from it's initial discussion, so I have created a new issue and closed this one. Please continue any sync settings and tokens discussion on the new issue: #102

**Comment by allo-** [comment]
Seems like setup 1 would still profit from server-side storage, as a setup-assistant should not show more than once, even when you use a other browser or device or delete your cookies.
An easier solution would be skip the setup, use reasonable defaults and just add a button on the main page if stuff is still unconfigured.
