### ISSUE TITLE
[Feature Request] When right clicking ability to copy track link from source 

### ISSUE THREAD

**Issue by ddelnano** [jaedb/spotmop#77]
I commonly use the share functionality in the official Spotify client to send my friends a song / album I just discovered.  Could this functionality be added?  I have no problem making a PR with the change but I just want to see if it would be accepted before I put any effort in.

Basically I just want some way to be able to copy / access the url of the spotify song.

**Comment by ddelnano** [comment]
@jaedb since you tagged it does that mean you would accept a contribution?

**Comment by jaedb** [comment]
@ddelnano Feel free to fork, make your change and make a pull request :-)

**Comment by ddelnano** [comment]
:+1:

**Comment by jaedb** [comment]
Preliminary version scheduled for release `2.6.5` as at f052e23235e669a76063c0475d17ab5bf2e099f5
