### ISSUE TITLE
Using Spotmop with mobile device

### ISSUE THREAD

**Issue by benjaminshell** [jaedb/spotmop#79]
I just installed mopidy and decided Spotmop would be a great client to use. However the screenshots show that I can use/control Spotmop with a mobile device. How do I go about doing this?

**Comment by jaedb** [comment]
@benshell15 Glad you've made the leap and given it a go :-)

To use it on your mobile device, you will need to know the IP address (or hostname) of the computer that is running Mopidy on your local network. You then go to this IP address + port 6680 (unless you've set a custom port) and Spotmop will work just like any other mobile-responsive website.

So for example my Mopidy server is 192.168.1.5, to use it on my Android that is connected via Wifi, I open Chrome and go to http://192.168.1.5:6680.

Hope this helps! Let me know if you need any further help.

**Comment by benjaminshell** [comment]
I entered 150.201.183.214:6680 and nothing happened. I figured I had to change something in the config file so I changed the hostname under http to 150.201.183.214 from 127.0.0.1. That didn't do anything either.

**Comment by jaedb** [comment]
Your Mopidy config file (ie `~/.config/mopidy/mopidy.conf`) will need to allow connections from all IP addresses. For example:

```
[mpd]
hostname = 0.0.0.0
[http]
hostname = 0.0.0.0
```

Then restart Mopidy server. From your phone, navigate to http://150.201.183.214:6680. This IP address looks like a remote IP address (not a local network) so you'll need to have port forwarding configured on your router. I would recommend ensuring your phone is on the same network as your Mopidy server.

For more reading: https://docs.mopidy.com/en/latest/ext/mpd/#confval-mpd/hostname

**Comment by benjaminshell** [comment]
I'm on a university network, so the router is managed by my school. I won't be able to enable port forwarding. Thank you for your help.

**Comment by jaedb** [comment]
Are your Mopidy server and phone devices both on the same network? If so, you should be able to connect without any port forwarding trickery. In any case, I'd look at the Mopidy documentation to allow connections from all IP addresses.
