### ISSUE TITLE
Adding to playlist on Mobile

### ISSUE THREAD

**Issue by snoopaki** [jaedb/spotmop#80]
Hello, great work on spotmop!

I am having a problem using it on my mobile device. I can't seem to add anything to a playlist via the context menu. The playlists show up but I can't "select" one.

I have the exact same problem on a regular browser when "Emulate Touch Device" is enabled. I choose the tracks, select add to playlist, my playlists show up as icons but I can't choose one!!!

Other than that great job, enjoying spotmop!

**Comment by jaedb** [comment]
@snoopaki You're dead right! I'll make sure this is fixed in the next release :-)

**Comment by jaedb** [comment]
Resolved in 5818c090245881a179482dc840507d2112e977ba and will be in release `2.6.3`
