### ISSUE TITLE
CSS/styling issue apache mopidy mobile devices

### ISSUE THREAD

**Issue by gaiterjones** [jaedb/spotmop#82]
I am seeing some sort of CSS / styling issue with mobile devices when I access spotmop on the mopidy server via an apache website (http://server/mywebsite/spotmop).

On desktop devices spotmop renders correctly, on mobile devices elements do not seem to be styled correctly i.e. the now playing page is completely unstyled.

On desktops spotmop looks and works fine, on mobile devices styling is not correct.

When I access spotmop via mopidy (http://server:6680/spotmop) mopidy works and renders correctly for desktop and mobile devices.

**Comment by jaedb** [comment]
@gaiterjones Can you please send some screenshots? Also, what directory are you referencing as your apache `DocumentRoot`? `/src` or `/mopidy_spotmop/static/`?

**Comment by gaiterjones** [comment]
http://server/spotmop references /src where /spotmop is an alias. I see the same results when /src is also document root.

Desktop access works fine, mobile access is unstyled. Mobile access via mopidy 6680 works fine.

Left pic mobile via mopidy (TCP6680), right pic mobile via Apache/2.4.10 (Raspbian) document root as /src from github.

![spotmop](https://cloud.githubusercontent.com/assets/3909886/14673146/66bbca1e-06fc-11e6-959a-884befcee722.jpg)

**Comment by jaedb** [comment]
@gaiterjones Try setting your `DocumentRoot` up one level (so `/var/www/mopidy/` in place of `/var/www/mopidy/src`). Then access the interface via `http://myip/src/`.
