### ISSUE TITLE
Blank artist page

### ISSUE THREAD

**Issue by raymiec** [jaedb/spotmop#88]
Could not find any way to manually populate the artists page, i assume the data is taken from spotify, in that case i get a 403 when the client is making the call.

GET https://api.spotify.com/v1/me/following?type=artist

403 Forbidden   828ms

response 

  "error": {
    "status": 403,
    "message": "Insufficient client scope"

possibly not enough permission when authentication spotify api?

I gave it all the permission it asked for upon connecting.

**Comment by jaedb** [comment]
When you say _manually populate the artists page_, what do you mean exactly?

**Comment by raymiec** [comment]
Saving favourites from spotify, i.e follow artist. I'm guessing the expected functionality when clicking on Artists on the left menu is that it will populate the list from the spotify api with a a list of artists you follow?

**Comment by raymiec** [comment]
i get the same error on an artists page which contains the follow button, also 403, so even if im following an artist it wont be reflected on the button, i.e it will still say follow.

**Comment by jaedb** [comment]
Can you try logging out of Spotify and re-authenticating? Or better yet, in _Settings_ click _Reset all settings_?

**Comment by raymiec** [comment]
I reset all I reset all settings, problem still persists, heres a list of permissions i granted it 
- 
- Read your publicly available information
- Manage your private playlists
- Manage your public playlists
- Access your private playlists
- Manage your private playlists
- Access your saved tracks and albums
- Manage your saved tracks and albums
- Manage who you are following
- Read your top artists and tracks 

Manage artist a separate permission?

**Comment by jaedb** [comment]
I'm confused as to where you're selecting the permissions you want to grant. You either grant Spotmop access to it's defined permissions or you don't, there isn't anywhere you can pick and choose those permissions.

Can you please provide me with the following:
- Browser version(s)
- OS and version
- Mopidy version
- Mopidy-Spotify version
- Spotmop version

This will help me try and replicate the issues you're experiencing. At this stage I cannot replicate the issue.

**Comment by raymiec** [comment]
thats the list it ask for when authenticating. As you said i can choose to accept or deny all of them.   laptop  browser: chrome Version 50.0.2661.94 m      OS windows 8.1      i have the latest ver of mopidy from apt.mopidy.com runnin on a pi2 model b.  mopidy spotify version i assume the latest, i've switched the pi off for tonight so i can't confirm. and v 2.6.4.   I can attach some screenshots and console output tomorrow.

mobile info  cm12.1  chrome v 49.0.2623.105

**Comment by raymiec** [comment]
Can you post your spotify authentication script from your server, i assume thats where the client scope for spotify is held,   Whats stopping us using the access tokens from the mopidy spotify service? it might already have all the permissions required, it would also eliminate the need for users to login from every device. if i have people over i don't want to have to give every person my spotify login details in order to use the app, This should be a core feature i.m.o

**Comment by raymiec** [comment]
another related authentication bug, when trying to authenticate within an android webview.

I get that in the console after clicking okay to authenticate spotify, i then expect to be redirected to the app but a page just displaying "Error!"

04-30 18:27:01.278: I/chromium(6784): [INFO:CONSOLE(3)] "Uncaught TypeError: Cannot read property 'postMessage' of null", source: http://jamesbarnsley.co.nz/spotmop.php?code=AQBLiyHhJoCVCLmxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by raymiec** [comment]
to fix the blank artist page add user-follow-read to the scope

**Comment by jaedb** [comment]
I've added `user-follow-read` to the scopes requested. Can you confirm this has resolved the issue?

**Comment by raymiec** [comment]
Yeah i get the correct response now. 

{
  "artists" : {
    "items" : [ {
      "external_urls" : {
        "spotify" : "https://open.spotify.com/artist/0k17h0D3J5VfsdmQ1iZtE9"
      },...

**Comment by raymiec** [comment]
it also fixes the issue with the follow button.

**Comment by jaedb** [comment]
Sweet! Thanks for the help :-)
