### ISSUE TITLE
Feature request: Create playlist, from selected track

### ISSUE THREAD

**Issue by LasseSLambertsen** [jaedb/spotmop#99]
Hey James,

It would be nice, if there were a option, to play all tracks following a single tracks, ie. I'm listening to a playlist, and then goes to play a track from a different playlist or My Tracks, then just play all the tracks in that playlist :)

**Comment by jaedb** [comment]
Hey man,

I'm not 100% sure what you're after. Is this not functionality covered by the "Play next" context menu (and drag-and-drop zone)?

**Comment by LasseSLambertsen** [comment]
Having a trouble explaining this, second language and such 😆 
The functionality I'm requesting, is when I double click on a track. Then it and the other tracks on its playlist, album etc. will replace the current play queue. 
I'm pretty sure the functionality has been there before, but can't get it to work now :) 

I'm actually pretty certain that Spotify themselves does it like this :)

**Comment by jaedb** [comment]
Ah, I understand now! Yes, this is how it used to work however it seemed a little counter-intuitive. The main reason was that in a shared environment (ie an office or busy home) people tended to double-click tracks to play them without realising that it wiped the queue that someone else had setup.

The best example was imagine a party soundtrack that you queue up. Then people want to play certain songs, so they search for them and double-click on one of the results. This then kills the entire queue and plays all the results. The same was true for playlists.

At this point there isn't really the scope to set this up so there was a setting to specify how you'd like this to work. It's one or the other (for now!).

**Comment by jaedb** [comment]
See #91 and #68 for the initial discussions.

**Comment by LasseSLambertsen** [comment]
Aah i see. That does actually make pretty good sense. 
Thanks for the heads up
